services:
  hmm-test:
    container_name: hmm-test
    image: ${HMM_TEST_IMAGE:?HMM_TEST_IMAGE must be set}
    env_file:
      - .env.test
    volumes:
      - ./var/test:/var/db
    command:
      - unitd
      - --no-daemon
      - --control
      - unix:/var/run/control.unit.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.hmm-test.rule=Host(`test.how-much-money.ru`)
      - traefik.http.routers.hmm-test.entrypoints=websecure
      - traefik.http.routers.hmm-test.tls.certresolver=letsencrypt
      - traefik.http.routers.hmm-test.middlewares=hmm-test-auth
      - traefik.http.middlewares.hmm-test-auth.basicauth.users=${TEST_BASIC_AUTH:?TEST_BASIC_AUTH must be set}
      - traefik.http.services.hmm-test.loadbalancer.server.port=80
    networks:
      - web
      - hmm_test_net
    restart: unless-stopped

networks:
  web:
    external: true
  hmm_test_net:
    name: hmm_test_net
